### ISSUE TITLE
Popup is loading without caroussel

### ISSUE THREAD

**Issue by boban-dj** [andresams/magento2-cart-popup#1]
Hi, the pop is loading without random or any other product setting.
It seems PopupCartData class not returning anything.
Was this work in progress?
thanks

**Comment by andresams** [comment]
Nope, this is working and it was even tested on different Magento installations. Which Magento version are you using?

**Comment by boban-dj** [comment]
2.3.2-p2, what kind of products do you have? i tried with random, bestseller setting but no products only the popup. I will debug some more

**Comment by andresams** [comment]
I tested using the official sample data. Your issue may be related to the status and visibility filters that I added to the collection. Please, check this file:

https://github.com/andresams/magento2-cart-popup/blob/master/popup-display/CustomerData/PopupCartData.php

Lines 142 and 146. You can try removing these filters.

 It also would be great if you could open your browser console and see what is being returned by the request that is made after the product is added to the cart (the products should be returned on this request).

**Comment by boban-dj** [comment]
Yes it was working now, but I think there is another issue on my side with session in browser.
will check and let you know, thanks
