### ISSUE TITLE
sprintf(): Too few arguments

### ISSUE THREAD

**Issue by in-session** [andresams/magento2-cart-popup#3]
We get the following error message on Magento 2.3.5

1 exception(s):
Exception #0 (Exception): Warning: sprintf(): Too few arguments in /html/magento2/vendor/prestafy/magento2-cart-popup/popup-display/Block/Popup.php on line 55

**Comment by andresams** [comment]
I could not reproduce this issue. Please, add the steps to reproduce it in case it is still happening.
